# Generated by Django 3.0.4 on 2020-04-16 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_category_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
