# Generated by Django 3.0.4 on 2020-04-21 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20200418_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp', 'title']},
        ),
    ]
